    LIST P = 16F628A
    INCLUDE "P16F628A.INC"
    __CONFIG _XT_OSC & _WDT_OFF &_PWRTE_ON &_BODEN_OFF &_LVP_OFF &_CP_OFF &_CPD_OFF &_MCLRE_ON 
    
SAYAC1 EQU h'20'
SAYAC2 EQU h'21'
    ORG h'00'
    CLRF PORTB
    BANKSEL TRISB
    CLRF TRISB
    BANKSEL PORTB
    
BASLA
    MOVLW h'AA'
    MOVWF PORTB
    CALL GECIKME
    
    MOVLW h'55'
    MOVWF PORTB
    CALL GECIKME
    
    GOTO BASLA
    
GECIKME
    MOVLW h'FF'
    MOVWF SAYAC1
DONGU1
    MOVLW h'FF'
    MOVWF SAYAC2
DONGU2
    DECFSZ SAYAC2, F
    GOTO DONGU2
    DECFSZ SAYAC1, F
    GOTO DONGU1
    RETURN
    END

