    LIST P = 16F628A
    INCLUDE "P16F628A.INC"
    __CONFIG _XT_OSC & _WDT_OFF &_PWRTE_ON &_BODEN_OFF &_LVP_OFF &_CP_OFF &_CPD_OFF &_MCLRE_ON 
    
    ORG h'00'
    CLRF PORTB
    BANKSEL TRISB
    CLRF TRISB
    BANKSEL PORTB
BASLA
    MOVLW h'55'
    MOVWF TRISB
DONGU
    GOTO DONGU
    END


